/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["liveness_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities */
        get: operations["capabilities_v1_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cases */
        get: operations["list_cases_v1_cases_get"];
        put?: never;
        /** Create Case */
        post: operations["create_case_v1_cases_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Case */
        get: operations["get_case_v1_cases__case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{case_id}/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Case Scans */
        get: operations["list_case_scans_v1_cases__case_id__scans_get"];
        put?: never;
        /** Create Scan */
        post: operations["create_scan_v1_cases__case_id__scans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/scans/{scan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scan */
        get: operations["get_scan_v1_scans__scan_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/scans/{scan_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Scan */
        post: operations["cancel_scan_v1_scans__scan_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/scans/{scan_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scan Events */
        get: operations["scan_events_v1_scans__scan_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/scans/{scan_id}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Graph */
        get: operations["get_graph_v1_scans__scan_id__graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdapterRun */
        AdapterRun: {
            /** Adapter Id */
            adapter_id: string;
            /** Adapter Version */
            adapter_version: string;
            /**
             * Attempts
             * @default 0
             */
            attempts: number;
            /** Case Id */
            case_id: string;
            /**
             * Finding Count
             * @default 0
             */
            finding_count: number;
            /** Finished At */
            finished_at?: string | null;
            /** Id */
            id?: string;
            /**
             * Latency Seconds
             * @default 0
             */
            latency_seconds: number;
            /** Outcome Code */
            outcome_code?: string | null;
            /** Owner Id */
            owner_id: string;
            /** Scan Id */
            scan_id: string;
            source_target: components["schemas"]["ScanTarget"];
            /** Started At */
            started_at?: string | null;
            state: components["schemas"]["AdapterState"];
        };
        /**
         * AdapterState
         * @description Truthful terminal states for one adapter invocation.
         * @enum {string}
         */
        AdapterState: "queued" | "running" | "unavailable" | "succeeded" | "no_results" | "retryable_failure" | "failed";
        /** CapabilitiesResponse */
        CapabilitiesResponse: {
            /** Adapters */
            adapters: components["schemas"]["CapabilityAdapter"][];
            /** Dependencies */
            dependencies: {
                [key: string]: boolean;
            };
            policy: components["schemas"]["CapabilityPolicy"];
        };
        /** CapabilityAdapter */
        CapabilityAdapter: {
            /** Adapter Id */
            adapter_id: string;
            /** Display Name */
            display_name: string;
            /** Enabled */
            enabled: boolean;
            /** Max Attempts */
            max_attempts: number;
            /** Passive */
            passive: boolean;
            /** Target Types */
            target_types: string[];
            /** Unavailable Reason */
            unavailable_reason?: string | null;
        };
        /** CapabilityPolicy */
        CapabilityPolicy: {
            /** Active Scanning Authorized */
            active_scanning_authorized: boolean;
            /** Active Scanning Enabled */
            active_scanning_enabled: boolean;
            /** Active Scope Configured */
            active_scope_configured: boolean;
            /** Max Batch Size */
            max_batch_size: number;
            /**
             * Passive Default
             * @default true
             */
            passive_default: boolean;
        };
        /** Case */
        Case: {
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Description */
            description?: string | null;
            /** Id */
            id?: string;
            /** Name */
            name: string;
            /** Owner Id */
            owner_id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
        };
        /** CaseCreate */
        CaseCreate: {
            /** Description */
            description?: string | null;
            /** Name */
            name: string;
        };
        /** GraphEdge */
        GraphEdge: {
            /** Case Id */
            case_id: string;
            /** Id */
            id?: string;
            /** Owner Id */
            owner_id: string;
            /** Relationship */
            relationship: string;
            /** Scan Id */
            scan_id: string;
            /** Source Node Id */
            source_node_id: string;
            /** Target Node Id */
            target_node_id: string;
        };
        /** GraphNode */
        GraphNode: {
            /** Case Id */
            case_id: string;
            /**
             * Entity Type
             * @enum {string}
             */
            entity_type: "username" | "email" | "phone" | "domain" | "ip" | "url" | "company" | "vulnerability" | "cve" | "repository" | "cloud_storage" | "breach" | "dark_web_forum";
            /** Id */
            id?: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Owner Id */
            owner_id: string;
            /** Scan Id */
            scan_id: string;
            /** Value */
            value: string;
        };
        /** GraphPage */
        GraphPage: {
            /** Edges */
            edges?: components["schemas"]["GraphEdge"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Nodes */
            nodes?: components["schemas"]["GraphNode"][];
            /** Provenance */
            provenance?: components["schemas"]["Provenance"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Provenance */
        Provenance: {
            /** Adapter Version */
            adapter_version: string;
            /** Case Id */
            case_id: string;
            /** Confidence */
            confidence: number;
            /** Edge Id */
            edge_id?: string | null;
            /** Id */
            id?: string;
            /** Node Id */
            node_id?: string | null;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at?: string;
            /** Owner Id */
            owner_id: string;
            /** Scan Id */
            scan_id: string;
            /** Source Adapter Id */
            source_adapter_id: string;
            /** Source Relationship */
            source_relationship: string;
            source_target: components["schemas"]["ScanTarget"];
        };
        /** Scan */
        Scan: {
            /** Active Authorized At */
            active_authorized_at?: string | null;
            /** Active Authorized By */
            active_authorized_by?: string | null;
            /**
             * Active Scan Confirmed
             * @default false
             */
            active_scan_confirmed: boolean;
            /** Active Scope */
            active_scope?: string[];
            /** Adapter Ids */
            adapter_ids?: string[] | null;
            /**
             * Cancel Requested
             * @default false
             */
            cancel_requested: boolean;
            /** Case Id */
            case_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Finished At */
            finished_at?: string | null;
            /** Id */
            id?: string;
            /** Job Id */
            job_id?: string | null;
            /** @default passive */
            mode: components["schemas"]["ScanMode"];
            /** Outcome Code */
            outcome_code?: string | null;
            /** Owner Id */
            owner_id: string;
            /** Started At */
            started_at?: string | null;
            /** @default queued */
            state: components["schemas"]["ScanState"];
            /** Targets */
            targets: components["schemas"]["ScanTarget"][];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
            /**
             * Worker Attempt
             * @default 0
             */
            worker_attempt: number;
        };
        /** ScanCreate */
        ScanCreate: {
            /**
             * Active Scan Confirmed
             * @default false
             */
            active_scan_confirmed: boolean;
            /** Adapter Ids */
            adapter_ids?: string[] | null;
            /** @default passive */
            mode: components["schemas"]["ScanMode"];
            /** Targets */
            targets: components["schemas"]["ScanTarget"][];
        };
        /** ScanDetail */
        ScanDetail: {
            /** Active Authorized At */
            active_authorized_at?: string | null;
            /** Active Authorized By */
            active_authorized_by?: string | null;
            /**
             * Active Scan Confirmed
             * @default false
             */
            active_scan_confirmed: boolean;
            /** Active Scope */
            active_scope?: string[];
            /** Adapter Ids */
            adapter_ids?: string[] | null;
            /** Adapter Runs */
            adapter_runs?: components["schemas"]["AdapterRun"][];
            /**
             * Cancel Requested
             * @default false
             */
            cancel_requested: boolean;
            /** Case Id */
            case_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Finished At */
            finished_at?: string | null;
            /** Id */
            id?: string;
            /** Job Id */
            job_id?: string | null;
            /** @default passive */
            mode: components["schemas"]["ScanMode"];
            /** Outcome Code */
            outcome_code?: string | null;
            /** Owner Id */
            owner_id: string;
            /** Started At */
            started_at?: string | null;
            /** @default queued */
            state: components["schemas"]["ScanState"];
            /** Targets */
            targets: components["schemas"]["ScanTarget"][];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
            /**
             * Worker Attempt
             * @default 0
             */
            worker_attempt: number;
        };
        /**
         * ScanMode
         * @enum {string}
         */
        ScanMode: "passive" | "active";
        /**
         * ScanState
         * @enum {string}
         */
        ScanState: "queued" | "running" | "succeeded" | "partial" | "failed" | "cancelled";
        /** ScanTarget */
        ScanTarget: {
            /**
             * Target Type
             * @enum {string}
             */
            target_type: "username" | "email" | "phone" | "domain" | "ip" | "url" | "company" | "vulnerability" | "cve" | "repository" | "cloud_storage" | "breach" | "dark_web_forum";
            /** Target Value */
            target_value: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    liveness_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Operations-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Operations-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    capabilities_v1_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilitiesResponse"];
                };
            };
        };
    };
    list_cases_v1_cases_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Case"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_case_v1_cases_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Case"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_case_v1_cases__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Case"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_case_scans_v1_cases__case_id__scans_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scan"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_scan_v1_cases__case_id__scans_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scan_v1_scans__scan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_scan_v1_scans__scan_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_events_v1_scans__scan_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_graph_v1_scans__scan_id__graph_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
